version: '3'
services:
  config:
    build: ./jcconf2018-config
  eureka:
    build: ./jcconf2018-eureka
    restart: on-failure
    ports:
      - 8000:8000
  admin:
    build: ./jcconf2018-admin
    restart: on-failure
    ports:
    - 30000:80
  service:
    build: ./jcconf2018-service
    restart: on-failure
  feign:
    build: ./jcconf2018-feign
    restart: on-failure
  gateway:
    build: ./jcconf2018-gateway
    restart: on-failure
    ports:
      - 8080:80
