version: '3'
services:
  config:
    build: ./jcconf2018-config
    ports:
      - 8888:8888
  eureka:
    build: ./jcconf2018-eureka
    restart: on-failure
    ports:
      - 8000:8000
  service:
    build: ./jcconf2018-service
    restart: on-failure
#    environment:
#      - APP_OPTS=-Deureka.instance.hostname=localhost -Deureka.instance.non-secure-port=8081
#    ports:
#      - 8081:80
  gateway:
    build: ./jcconf2018-gateway
    restart: on-failure
    ports:
      - 8080:80
